# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: xenial
sudo: false
language: python

notifications:
  email: change

matrix:
  include:
    - os: linux
      python: "3.4"
    - os: linux
      python: "3.7"
    - os: linux
      python: "3.8"

    - os: osx
      # python comes with `osx_image`, see
      # https://blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci
      language: shell
      osx_image: xcode10.2

branches:
  only:
    - master
    - travis

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

    packages:
    - libgtk-3-dev
    - libgtk-3-0
    - libstdc++-6-pic


before_install:
  - set -e
  - python3 --version

install:
  - export SDK_URL=https://raw.githubusercontent.com/c-smile/sciter-sdk/master
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then curl -so "$TRAVIS_BUILD_DIR/libsciter-gtk.so" $SDK_URL/bin.lnx/x64/libsciter-gtk.so; fi
  - if [ "$TRAVIS_OS_NAME" = "osx"   ]; then curl -so "$TRAVIS_BUILD_DIR/sciter-osx-64.dylib" $SDK_URL/bin.osx/sciter-osx-64.dylib; fi

  - pip3 install -U pip
  - pip3 install -U pytest

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:$TRAVIS_BUILD_DIR"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cp "$TRAVIS_BUILD_DIR/sciter-osx-64.dylib" "$TRAVIS_BUILD_DIR/libsciter-osx-64.dylib"; fi

  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$TRAVIS_BUILD_DIR"; fi

  - export PATH="$PATH:$TRAVIS_BUILD_DIR"
  - export LIBRARY_PATH="$LIBRARY_PATH:$TRAVIS_BUILD_DIR"

script:
  - python3 setup.py develop
  - python3 tests/test_value.py

after_script: set +e
